### ISSUE TITLE
Pagination Labels not Working

### ISSUE THREAD

**Issue by znenet** [julekgwa/react-native-app-onboard#1]
Hi @julekgwa!
I came across your library after running into the: "Support for defaultProps will be removed from function components in a future major release." errors in the react-native-onboarding-swiper library.
Thank you so much for fixing those!
However, my App is localized and it looks like you aren't passing skipLabel, nextLabel, and doneLabel down to Pagination.tsx.
Could you fix that please, so I can use these props?
That would be fantastic!
Thanks again for this great libary!

**Comment by znenet** [comment]
"paginationContainerStyle" also seems to not be passed down to Pagination.tsx

**Comment by julekgwa** [comment]
@znenet fix is in the latest version. 0.1.7

**Comment by znenet** [comment]
Awesome! Thank you so much for the quick fix. Just tested the 3 labels and they are all 3 working now. However, "paginationContainerStyle" still seems to not be passed down to Pagination.tsx, could you have a look at that as well, please?

Looking at Swiper.tsx, it looks like you are passing it correctly in case of CustomPages, but not in the "OnboardingPages" case.

**Comment by julekgwa** [comment]
Updated

**Comment by znenet** [comment]
Thanks! Can you fix one more thing. I feel bad being such a pain. But my localized language is German and the Word for "Skip" is "Überspringen", which is super long and looks bad in the bottom right in the pagination bar.
Therefore, I just used the "skipButtonPosition" property to move it to the "top-right". Unfortunately, SkipButton is not passing the skipLabel.

When I change it to the following, it works as expected.:

```
<SkipButton
          buttonTextStyle={props.skipLabelStyle}
          buttonStyle={props.skipButtonContainerStyle}
          position={props.skipButtonPosition}
          onPress={props.onSkip}
          label={props.skipLabel}
        />
```

Note the `label={props.skipLabel}`

**Comment by julekgwa** [comment]
@znenet it does pass it look at this example https://snack.expo.dev/@lekgwaraj/react-native-app-onboard

**Comment by znenet** [comment]
Sorry, should have been more specific. It does work for "pages" you are correct! It does not work for CustomPages, which is what I am using.

**Comment by julekgwa** [comment]
Updated. Please install v0.1.9 https://snack.expo.dev/@lekgwaraj/react-native-app-onboard-custom-pagination?platform=ios

**Comment by znenet** [comment]
Thank you!
